name: .NET

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Zip artifacts
      shell: powershell
      run: Compress-Archive -Path $(Get-ChildItem .\src\KG.Map\bin\Debug\net8.0-windows -Exclude *.pdb) -DestinationPath kg.map-${{ github.event.release.tag_name }}.zip
    - name: upload release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: kg.map-${{ github.event.release.tag_name }}.zip
        asset_name: kg.map-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
